[package]
name = "onisoft_launcher"
version = "0.5.1"
description = "Onisoft Launcher"
authors = ["Onivoid"]
edition = "2021"

[lib]
name = "onisoft_launcher_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["image-png"] }
tauri-plugin-opener = "2"
tauri-plugin-updater = "2.10.0"
tauri-plugin-process = "2.3.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls", "stream"] }
tokio = { version = "1", features = ["fs", "io-util", "macros", "rt-multi-thread", "time"] }
futures-util = "0.3"
chrono = { version = "0.4", features = ["serde"] }
glob = "0.3"
